### ISSUE TITLE
moduleCheckUnused task not found

### ISSUE THREAD

**Issue by tasomaniac** [RBusarow/ModuleCheck#403]
When I run according to docs `./gradlew moduleCheckUnused` the task is not found. When I grep all the tasks, I got the output like this. Do I do anything wrong?

```

moduleCheck - runs all enabled ModuleCheck rules
moduleCheckAuto - runs all enabled ModuleCheck rules
moduleCheckDepths - The longest path between this module and its leaf nodes
moduleCheckDepthsAuto - The longest path between this module and its leaf nodes
moduleCheckGraphs - The longest path between this module and its leaf nodes
moduleCheckGraphsAuto - The longest path between this module and its leaf nodes
moduleCheckSortDependencies - Sorts all dependencies within a dependencies { ... } block
moduleCheckSortDependenciesAuto - Sorts all dependencies within a dependencies { ... } block
moduleCheckSortPlugins - Sorts Gradle plugins which are applied using the plugins { ... } block
moduleCheckSortPluginsAuto - Sorts Gradle plugins which are applied using the plugins { ... } block
```

**Comment by RBusarow** [comment]
Thanks for the report!  The task list was getting pretty out of hand, so I switched it to basically just be the main `moduleCheck[Auto]` task with properties for toggling individual checks.

The docs are versioned, and the snapshot versions are (mostly) documented with the "next" version here: https://rbusarow.github.io/ModuleCheck/docs/next/

I've got a few things to do here:
- [ ] update the "next" docs with the correct task list.
- [ ] make it obvious that a SNAPSHOT version should use the "next" docs as a reference
- [ ] stop generating the `moduleCheckDepthsAuto` and `moduleCheckGraphsAuto` tasks, since there's nothing to auto-correct.
- [ ] update the image in the main README and the website, because `moduleCheckApply` isn't a task and I should never have put that into a static image...

**Comment by tasomaniac** [comment]
Ah ok. Thanks for clarifying. It is not everyday that users will have snapshot builds. Indeed I was using snapshot to have the other issue fixed. Thanks for the awesome work. All good for me. It definitely makes sense to do this based on configuration rather than having explosion of tasks.
